# see orb options at
# https://github.com/cypress-io/circleci-orb
version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  first:
    executor: cypress/base-10
    steps:
      - checkout
      - run: pwd
      - run: ls -la .
      - persist_to_workspace:
          root: ~/
          paths:
          - project

  second:
    executor: cypress/base-10
    parallelism: 3
    steps:
      - attach_workspace:
          at: ~/
      - run: pwd
      - run: ls -la .
      # add another file
      - run: echo "Job node index $CIRCLE_NODE_INDEX" > foo-$CIRCLE_NODE_INDEX.json
      - persist_to_workspace:
          root: ~/
          paths:
          - project/foo*.json
      - run: ls -la .

  third:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: pwd
      - run: ls -la .
      - run: ls -la ~
      - run: ls -la /

workflows:
  build:
    jobs:
      - first
      - second:
          requires:
            - first
      - third:
          requires:
            - second
